### ISSUE TITLE
Error on login or sign: "The relying party ID is not a registrable domain suffix of, nor equal to the current domain"

### ISSUE THREAD

**Issue by jpdreamos** [tkhq/demo-viem-passkeys#9]
Hi there, I successfully created a user, but when I attempt to either sign a message or login I get this error:

<img width="265" alt="image" src="https://github.com/user-attachments/assets/d123f72d-c533-41d4-a7d8-356885ce751c">

```
SecurityError: The relying party ID is not a registrable domain suffix of, nor equal to the current domain.
```

https://github.com/user-attachments/assets/c128d46c-7408-4ee7-a0d6-0bfa70db4315

**Comment by taylorjdawson** [comment]
@jpdreamos can you try and remove the comments at the end of the env vars for RPID and server sign url? 

https://github.com/tkhq/demo-viem-passkeys/blob/053d793892c0c33f636fcf336bcb15f0799c5035/.env.local.example#L5-L6

I just reproed and it looks like it is an env parsing error 

Logging the config for the turnkey provider looks like this (before removing the EOL comments)
```
{
    "defaultOrganizationId": "70189536-9086-4810-a9f0-990d4e7cd622",
    "rpId": "\"localhost\" # replace with domain in production",
    "serverSignUrl": "http://localhost:3000/api # replace with backend URL in production",
    "iframeUrl": "https://auth.turnkey.com"
}
```
Will update the .env.example and move the comments above the vars to avoid this in the future
